#!/usr/bin/env pwsh

# Stop on every error
$script:ErrorActionPreference = 'Stop'

# For an overview of all available styles, see:
# * https://xyproto.github.io/splash/docs/all.html (short snippets)
# * https://xyproto.github.io/splash/docs/longer/all.html (longer snippets)
$THEME = 'catppuccin-macchiato'

# Adopt these colors from the selected theme.
$BACKGROUND_COLOR = '#24273a'
$TEXT_COLOR = '#cad3f5'
$LINE_NUMBER_COLOR = '#8087a2'
$COMMENT_SELECTION_COLOR = 'white'

####################################################################################

$output = & hugo gen chromastyles --style $THEME
if (-Not $?) {
    Write-Host $output
    Write-Error 'hugo gen failed'
}

$cssRules = $output -join "`n" | Out-String

$cssFileContents = @"
//
// This file has been generated by "$($MyInvocation.MyCommand.Name)".
//
// DO NOT MODIFY MANUALLY!!!
//
// Theme: $THEME
//

`$code-block-background-color: $BACKGROUND_COLOR;
`$code-block-text-color: $TEXT_COLOR;
`$code-block-line-number-color: $LINE_NUMBER_COLOR;

&::selection, *::selection {
  background-color: rgba(`$code-block-text-color, .3);
}

.chroma {
  // Make comments easier to read when selected.
  .c, .ch, .cm, .c1, .cs, .cp, .cpf {
    &::selection {
      color: $COMMENT_SELECTION_COLOR;
    }
  }
}

$cssRules
"@

$cssFileContents.TrimStart().Replace("`r", '') | Out-File "$PSScriptRoot/css/components/_code_block_highlighting.scss" -Encoding utf8 -NoNewline
