#!/usr/bin/env pwsh

# Stop on every error
$script:ErrorActionPreference = 'Stop'

# For an overview of all available styles, see:
# * https://xyproto.github.io/splash/docs/all.html (short snippets)
# * https://xyproto.github.io/splash/docs/longer/all.html (longer snippets)
$THEME = 'catppuccin-macchiato'
$BACKGROUND_COLOR = '#24273a'
$TEXT_COLOR = '#cad3f5'

$output = & hugo gen chromastyles --style $THEME
if (-Not $?) {
    Write-Host $output
    Write-Error 'hugo gen failed'
}

$cssRules = $output -join "`n" | Out-String

$cssFileContents = @"
//
// This file has been generated by $($MyInvocation.MyCommand.Name).
//
// DO NOT MODIFY MANUALLY!!!
//
// Theme: $THEME
//

`$code-block-background-color: $BACKGROUND_COLOR;

&::selection, *::selection {
  background-color: rgba($TEXT_COLOR, .3);
}

$cssRules
"@

$cssFileContents.TrimStart().Replace("`r", '') | Out-File "$PSScriptRoot/css/components/_code_block_highlighting.scss" -Encoding utf8 -NoNewline
